### ISSUE TITLE
NPE caused by capability provider in Forge

### ISSUE THREAD

**Issue by ItsWavyy** [Theta-Dev/ConstructionWand#39] opened 2021-09-23 19:59 UTC
I dont really know what happened, but i was using a diamond wand to fill in some dirt, and it just stopped working. Now when i try to use it, nothing happens, and all the doors in my world get glitched after trying to place with it. Any advice?

**Comment by Theta-Dev** [comment] 2021-09-23 20:10
Could you give me some more information about the issue (MC version, other mods installed)?

**Comment by Theta-Dev** [comment] 2021-09-25 09:13
Also: what do you have in your inventory, are you in survival or creative mode and what do you mean with "glitched doors"? I cant reproduce the issue with only so few information.

**Comment by ItsWavyy** [comment] 2021-09-27 20:02
> Also: what do you have in your inventory, are you in survival or creative mode and what do you mean with "glitched doors"? I cant reproduce the issue with only so few information.

Im playing survival on a server i run with my friends, currently we have biomesoplenty, croptopia, mrcrayfish's furniture, ironchest, just enough items, mcw windows, travelers backpack, xaeros minimap, and xp tome.

ill include screenshots below of the doors, and my console log when i tried using the wand

![image_2021-09-27_155743](https://user-images.githubusercontent.com/90735646/134976357-029e713e-44bb-4a89-b425-69ff2f987428.png)

![image](https://user-images.githubusercontent.com/90735646/134977124-cd54bd7f-b209-4a27-91f1-4b0ed08d4013.png)

![image_2021-09-27_160556](https://user-images.githubusercontent.com/90735646/134977465-26a6c3e2-2639-4cd3-a6ea-2e93668f38c6.png)

**Comment by Theta-Dev** [comment] 2021-09-27 20:41
That section of the server console does not give me much information. It looks like it shows the stack trace of an error, but I can only see the last 3 lines.
Could you upload the entire error log to Pastebin?

Also, what Minecraft version are you playing on?

**Comment by ItsWavyy** [comment] 2021-09-28 16:34
Im playing minecraft 1.17.1, ill include pictures of a whole console log below with the errors

![Screenshot (4)](https://user-images.githubusercontent.com/90735646/135128602-2478e971-00f9-4bd2-bacf-33300daeca9e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/90735646/135128619-55d210cd-3d04-4479-8c8a-59b2ece51dd6.png)
![Screenshot (6)](https://user-images.githubusercontent.com/90735646/135128621-217ae46e-ccbd-40c2-ae7e-f2f9e676065c.png)
![Screenshot (7)](https://user-images.githubusercontent.com/90735646/135128623-67532499-7432-4d3a-9fd7-a4c7882d07e5.png)

**Comment by Theta-Dev** [comment] 2021-09-28 19:28
I have looked into the issue and it seems like a bug in Forge.
Are you using Forge version 37.0.66? If yes, they reworked the capability provider in that version but created a bug that can cause a NPE when querying an item's capabilities. So when ConstructionWand asks Forge if an item has the ItemHandlerCapability (is a modded item container like a backpack), it may throw an error.

See this issue for details https://github.com/MinecraftForge/MinecraftForge/issues/8093

Updating Forge should fix the issue, in fact they released a hotfix just within 2 hours. Guess you had bad luck when installing forge ;-)

**Comment by Theta-Dev** [comment] 2021-09-28 19:47
Update: I have seen in the logs that you are using Forge 37.0.68.
They released another fix for this issue with Forge 37.0.70, though.

I have tried to reproduce the error myself in different Forge versions, but it did not happen to me.

So you should install the latest Forge version and see if that fixes your issue.

**Closed as completed** 2021-10-04 11:22 UTC
