### ISSUE TITLE
Crash on block preview

### ISSUE THREAD

**Issue by ivanirucho** [Theta-Dev/ConstructionWand#64] opened 2022-12-24 14:16 UTC
minecraft crashes when rendering ANY block preview

[crash-2022-12-24_15.05.47-client.txt](https://github.com/Theta-Dev/ConstructionWand/files/10298727/crash-2022-12-24_15.05.47-client.txt)

**Comment by Theta-Dev** [comment] 2023-02-12 15:27
Could you tell me what Reliquary item(s) you had in your inventory when the crash occurred?
Reliquary has a couple of items that act as item containers, such as the *Void Tear*.

I have tested it and could not reproduce the crash, though. The log suggests that Reliquary returned a higher number of slots than the container actually has, resulting in an OutOfBounds error when querying them.

**Comment by ivanirucho** [comment] 2023-02-15 17:13
i ended up finding what caused it, it was the harvest rod

**Comment by Theta-Dev** [comment] 2023-02-15 19:58
This looks like an issue with the Reliquary mod and likely also occurs with other modded items that can extract items from containers (Forge has a standardized interface for this).

I have reported the issue, hopefully they can fix it quickly.

**Comment by Theta-Dev** [comment] 2024-01-24 15:59
closing, since it got fixed by Reliquary

**Closed as completed by Theta-Dev** 2024-01-24 15:59 UTC
